### PR TITLE
High-level Overhaul

### LINKED ISSUE #6: The Object Model
A step to the a high-level binding is to decide the object model to be used, each has pros and cons, mainly because of the C model used in IUP.

**Note:** The pros and cons lists are not exhaustive, please consider adding more if any comes to mind. 

**Terminology:**
- _string attributes_: Using `IupGetAttribute` and `IupSetAttribute` which gets and sets a string instead of a well specified object type.
- _function/methods for attributes_: Using a function/method for each attribute, giving more type safety to it since each of those functions will set/get the correct type of the attribute instead of a string.
### Ihandle and Functions _(using string attributes)_

This is the current model in the library, all the IUP objects are described with a `Ihandle` structure and passed to functions as the first argument.

Pros:
- Simple model.
- Maps 1:1 to IUP documentation

Cons:
- Attributes aren't type-safe.
- Not possible to find out about attributes by using auto-completion.
- Annoying `&mut handle` on each function call.
### Ihandle and Functions _(using functions for attributes)_

Pros
- Simple model.
- Maps almost 1:1 to IUP documentation.
- Type-safe attributes.
- Possible to find out about attributes by using auto-completion.

Cons:
- Annoying `&mut handle` on each function call.
### Ihandle and Methods

Mirror **Ihandle and Functions _(using string attributes)_** and **Ihandle and Functions _(using functions for attributes)_** here by excluding the _**Annoying `&mut handle` on each function call**_ cons.
### Structs/Traits and Methods  _(using methods for attributes)_

Pros:
- More Rusty
- Very type-safe.
- Possible to find out about attributes by using auto-completion + only the attributes and callbacks that applies to this object in question.

Cons:
-  Complex model.
- Does not map 1:1 to IUP documentation.

Issues:
- How to deal with functions that returns a handle to any kind of object (e.g. `IupGetHandle`)?

### PR DESCRIPTION
**Pull request by thelink2012**
Closes #6.
Opening this pull instead of merging straight away to master to discuss if it's all good.

### CODE REVIEW

**Comment by dcampbell24** [comment]
This generally looks pretty good to me, but a couple small things. The README.md should probably be updated to reflect the change in design and I am not a fan of glob importing everything into the top level module.

**Comment by thelink2012** [comment]
> I am not a fan of glob importing everything into the top level module.

I think that's not idiomatic either indeed, I'm still gasping those _darn_ patterns.
Is that now the correct way?

**Comment by dcampbell24** [comment]
Yeah that looks more idiomatic. There are a few exceptions where glob imports are used, but not many. There is a brief guideline [here](https://github.com/rust-lang/rust-guidelines/blob/master/style/imports.md). That repo also has some more guidelines and is a good read if you were not already aware of it.

I think some libraries also have special modules they create just for use in glob imports analogous to the std::prelude.

**Comment by thelink2012** [comment]
Do you prefer to update the README yourself? I really have no idea what to write there. Should I merge it now or after the readme update?

**Comment by dcampbell24** [comment]
Sure, I will update it myself. Feel free to merge. Thanks for the updates!

There was an error in some previous commit that caused a failed build, but it all looks good now.

**Pull request merged**
