### PR TITLE
Few changes

### PR DESCRIPTION
**Pull request by thelink2012**
**Changes**:
- `iup::open` returns a RAII object.
- Use slices instead of Vec arguments.
- Added `IupLoad` and `IupLoadBuffer`.

### CODE REVIEW

**Comment by dcampbell24** [comment]
What do you think of using a closure rather than RAII, since the iup object is not being used directly?

``` rust
fn with_iup<F: FnOnce() -> Result<(), String>>(func: F) -> Result<Iup, String> {
// do init
// call func and store the result
// do clean-up
// if there was an error calling the function return that error; otherwise, if there was an error during clean-up return that, otherwise return Ok.
}
```

**Comment by dcampbell24** [comment]
We could also run the main_loop automatically when the closure does not return an Error.

**Comment by thelink2012** [comment]
It seems like a good idea, however what if one wants to have direct control of the program flow and do the IUP loop steps by himself i.e. `IupLoopStep` / `IupFlush`?

**Comment by dcampbell24** [comment]
I think that situation could be handled separately. I am not very familiar how to use IupLoopStep. Is that something that could be made an Iterator?

**Comment by thelink2012** [comment]
My mistake, `IupLoopStep` is not a replacement for `IupMainLoop` I have misread the documentation.
The examples using `iup::with_iup` looks quite good :)

**Comment by dcampbell24** [comment]
Looks good, thanks!

**Pull request merged**
